
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COLON COMMA LBRACE NUMBER RBRACE STRINGinicio : objetoobjeto : LBRACE miembros RBRACEmiembros : parmiembros : miembros COMMA parpar : STRING COLON valorvalor : STRINGvalor : NUMBERvalor : objeto'
    
_lr_action_items = {'LBRACE':([0,9,],[3,3,]),'$end':([1,2,7,],[0,-1,-2,]),'STRING':([3,8,9,],[6,6,11,]),'RBRACE':([4,5,7,10,11,12,13,14,],[7,-3,-2,-4,-6,-5,-7,-8,]),'COMMA':([4,5,7,10,11,12,13,14,],[8,-3,-2,-4,-6,-5,-7,-8,]),'COLON':([6,],[9,]),'NUMBER':([9,],[13,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'inicio':([0,],[1,]),'objeto':([0,9,],[2,14,]),'miembros':([3,],[4,]),'par':([3,8,],[5,10,]),'valor':([9,],[12,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> inicio","S'",1,None,None,None),
  ('inicio -> objeto','inicio',1,'p_inicio','parser.py',7),
  ('objeto -> LBRACE miembros RBRACE','objeto',3,'p_objeto','parser.py',12),
  ('miembros -> par','miembros',1,'p_miembros_uno','parser.py',17),
  ('miembros -> miembros COMMA par','miembros',3,'p_miembros_varios','parser.py',23),
  ('par -> STRING COLON valor','par',3,'p_par','parser.py',32),
  ('valor -> STRING','valor',1,'p_valor_string','parser.py',39),
  ('valor -> NUMBER','valor',1,'p_valor_number','parser.py',44),
  ('valor -> objeto','valor',1,'p_valor_objeto','parser.py',49),
]
